const $ = (selector) => document.querySelector(selector);
const number = (value) => Number.parseFloat(value) || 0;
const foodStorageKey = 'diabetes-dashboard-food-entries';
const favoriteStorageKey = 'diabetes-dashboard-food-favorites';
const recentStorageKey = 'diabetes-dashboard-food-recents';
const recentByMealStorageKey = 'recent_foods_by_meal';
const carbTargetStorageKey = 'carbohydrate_count_settings';
const dailyDateStorageKey = 'diabetes-dashboard-food-date';
const themeToggle = $('#theme-toggle');
const foodSearchInput = $('#food-search-input');
const foodSearchResults = $('#food-search-results');
const foodSearchStatus = $('#food-search-status');
const foodEditor = $('#food-editor');
let foodIndex = [];
let currentResults = [];
let activeResult = -1;
let selectedFood = null;

const format = (value, suffix = '') => `${Number(value.toFixed(1)).toLocaleString('pt-BR')} ${suffix}`;
const formatNutrition = (carbs, calories) => `${format(carbs, 'g CHO')} · ${format(calories, 'kcal')}`;
const normalizeSearchText = (value) => String(value || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9\s]/g, ' ').replace(/\s+/g, ' ').trim();
const getStored = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key) || JSON.stringify(fallback)); } catch { return fallback; } };
const getEntries = () => getStored(foodStorageKey, []);
const getFavorites = () => getStored(favoriteStorageKey, []);
const getRecents = () => getStored(recentStorageKey, []);
const mealTypes = ['cafe_da_manha', 'almoco', 'lanche', 'jantar', 'ceia', 'outro'];
const getCarbTargets = () => getStored(carbTargetStorageKey, {});
const getRecentsByMeal = () => getStored(recentByMealStorageKey, {});
const todayKey = () => new Date().toLocaleDateString('en-CA');
function suggestedMeal() { const hour = new Date().getHours(); if (hour >= 5 && hour <= 10) return 'cafe_da_manha'; if (hour <= 14) return 'almoco'; if (hour <= 17) return 'lanche'; if (hour <= 22) return 'jantar'; return 'ceia'; }
function resetDailyEntriesIfNeeded() { if (localStorage.getItem(dailyDateStorageKey) === todayKey()) return; localStorage.setItem(foodStorageKey, '[]'); localStorage.setItem(dailyDateStorageKey, todayKey()); }

function setTheme(theme) { document.documentElement.dataset.theme = theme; const dark = theme === 'dark'; const label = dark ? 'Usar tema claro' : 'Usar tema escuro'; themeToggle.setAttribute('aria-label', label); themeToggle.title = label; themeToggle.setAttribute('aria-pressed', String(dark)); }
setTheme(localStorage.getItem('diabetes-dashboard-theme') || 'light');
themeToggle.addEventListener('click', () => { const theme = document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark'; localStorage.setItem('diabetes-dashboard-theme', theme); setTheme(theme); });

function getMonthKey(offset = 0) { const date = new Date(); date.setDate(1); date.setMonth(date.getMonth() + offset); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`; }
function updateMonthlyTotals() { const totals = getStored('diabetes-dashboard-monthly-insulin', {}); const previous = $('#previous-month-insulin'); const current = $('#current-month-insulin'); if (previous) previous.textContent = format(number(totals[getMonthKey(-1)]), 'un.'); if (current) current.textContent = format(number(totals[getMonthKey()]), 'un.'); }
function getCorrectionDose() { const factor = number($('#correction-factor').value); const current = $('#current-glucose').value; const target = $('#target-glucose').value; const difference = number(current) - number(target); const canCalculate = current && target && factor > 0; return { difference, canCalculate, dose: canCalculate && difference > 0 ? difference / factor : 0 }; }
function getCarbDose() { const entries = getEntries(); const meal = entries.at(-1)?.meal; const target = number(getCarbTargets()[meal]); if (!meal || target <= 0) return { canCalculate: false, dose: 0, carbs: 0, target: 0 }; const carbs = entries.filter((entry) => entry.meal === meal).reduce((total, entry) => total + number(entry.carbs), 0); return { canCalculate: true, dose: carbs / target, carbs, target }; }
function getInsulinDose() { const correction = getCorrectionDose(); const carbs = getCarbDose(); return { canCalculate: correction.canCalculate || carbs.canCalculate, dose: correction.dose + carbs.dose }; }
function updateCorrection() { const current = $('#current-glucose').value; const target = $('#target-glucose').value; const correction = getCorrectionDose(); const carbs = getCarbDose(); const insulin = getInsulinDose(); $('#glucose-difference').textContent = current && target ? `${correction.difference > 0 ? '+' : ''}${format(correction.difference, 'mg/dL')}` : '—'; $('#meal-dose').textContent = carbs.canCalculate ? `${format(carbs.carbs, 'g CHO')} ÷ ${format(carbs.target, 'g')} = ${format(carbs.dose, 'un.')}` : '—'; $('#correction-dose').textContent = insulin.canCalculate ? format(insulin.dose, 'un.') : '—'; }
['#target-glucose', '#correction-factor', '#current-glucose'].forEach((id) => $(id).addEventListener('input', updateCorrection));
['#target-glucose', '#correction-factor'].forEach((id) => { const key = id === '#target-glucose' ? 'diabetes-dashboard-target' : 'diabetes-dashboard-correction-factor'; const saved = localStorage.getItem(key) || (id === '#correction-factor' && localStorage.getItem('diabetes-dashboard-correction-insulin')); if (saved) $(id).value = saved; });
$('#save-parameters').addEventListener('click', () => { const status = $('#target-save-status'); const target = $('#target-glucose'); const factor = $('#correction-factor'); if (![target, factor].some((input) => input.value)) { status.textContent = 'Informe o alvo ou o valor de correção para gravar.'; target.focus(); return; } if (![target, factor].every((input) => !input.value || input.validity.valid)) { status.textContent = 'Informe valores válidos para gravar.'; return; } if (target.value) localStorage.setItem('diabetes-dashboard-target', target.value); if (factor.value) localStorage.setItem('diabetes-dashboard-correction-factor', factor.value); const dose = getInsulinDose().dose; if (dose > 0) { const totals = getStored('diabetes-dashboard-monthly-insulin', {}); const month = getMonthKey(); totals[month] = number(totals[month]) + dose; localStorage.setItem('diabetes-dashboard-monthly-insulin', JSON.stringify(totals)); updateMonthlyTotals(); status.textContent = 'Aplicação gravada no total deste mês.'; } else status.textContent = 'Parâmetros salvos; nenhuma aplicação foi adicionada ao mês.'; });

function loadCarbTargets() { const targets = getCarbTargets(); document.querySelectorAll('.carb-target').forEach((input) => { input.value = targets[input.dataset.meal] ?? ''; }); }
$('#save-carb-targets').addEventListener('click', () => { const inputs = [...document.querySelectorAll('.carb-target')]; const invalid = inputs.find((input) => input.value && !input.validity.valid); const status = $('#carb-target-status'); if (invalid) { status.textContent = 'Informe valores em gramas válidos.'; invalid.focus(); return; } const targets = {}; inputs.forEach((input) => { if (input.value !== '') targets[input.dataset.meal] = number(input.value); }); localStorage.setItem(carbTargetStorageKey, JSON.stringify(targets)); renderMeals(); status.textContent = 'Metas de carboidratos gravadas neste navegador.'; });

function renderMeals() { const entries = getEntries(); const targets = getCarbTargets(); const currentMeal = entries.at(-1)?.meal; let currentMealCarbs = 0; let currentMealCalories = 0; document.querySelectorAll('.meal-card').forEach((card) => { const list = card.querySelector('.meal-items'); const items = entries.filter((entry) => entry.meal === card.dataset.meal); const carbs = items.reduce((total, entry) => total + entry.carbs, 0); const calories = items.reduce((total, entry) => total + entry.calories, 0); const target = number(targets[card.dataset.meal]); if (card.dataset.meal === currentMeal) { currentMealCarbs = carbs; currentMealCalories = calories; } list.replaceChildren(); card.querySelector('.meal-empty').hidden = Boolean(items.length); const progress = card.querySelector('.meal-progress'); progress.textContent = target > 0 ? `Meta: ${format(target, 'g')} · Consumido: ${format(carbs, 'g')} · Restante: ${format(target - carbs, 'g')}` : `Consumido: ${format(carbs, 'g')} · Meta não configurada`; items.forEach((entry) => { const item = document.createElement('li'); item.className = 'meal-item'; const copy = document.createElement('span'); copy.innerHTML = `<strong>${entry.name}</strong><small>${entry.quantity} ${entry.unit} · ${formatNutrition(entry.carbs, entry.calories)}</small>`; const remove = document.createElement('button'); remove.type = 'button'; remove.className = 'remove-food'; remove.dataset.entryId = entry.entryId; remove.setAttribute('aria-label', `Remover ${entry.name}`); remove.textContent = '×'; item.append(copy, remove); list.append(item); }); card.querySelector('.meal-total strong').textContent = formatNutrition(carbs, calories); }); $('#daily-food-total').textContent = formatNutrition(currentMealCarbs, currentMealCalories); updateCorrection(); }
$('#meal-grid').addEventListener('click', (event) => { const button = event.target.closest('.remove-food'); if (!button) return; localStorage.setItem(foodStorageKey, JSON.stringify(getEntries().filter((entry) => entry.entryId !== button.dataset.entryId))); renderMeals(); });

function foodReference(food) { const amount = Number.isFinite(Number(food.quantidade_valor)) ? `${food.quantidade_valor} ${food.quantidade_unidade === 'g' ? 'g' : 'g/ml'}` : 'quantidade não informada'; return `${food.medida_usual || 'Medida não informada'} · ${amount}`; }
function rankFoods(query, foods = foodIndex) { const terms = normalizeSearchText(query).split(' ').filter(Boolean); const favorites = new Set(getFavorites()); const recent = getRecents(); const recentRank = new Map(recent.map((id, index) => [id, index])); return foods.filter((food) => !terms.length || terms.every((term) => food.search.includes(term))).sort((a, b) => { const score = (food) => (favorites.has(food.id) ? 40 : 0) + (recentRank.has(food.id) ? 20 - Math.min(recentRank.get(food.id), 19) : 0) + (food.search.startsWith(normalizeSearchText(query)) ? 10 : 0); return score(b) - score(a) || a.alimento.localeCompare(b.alimento, 'pt-BR'); }).slice(0, 12); }
function renderFoodResults(foods, label) { currentResults = foods; activeResult = -1; foodSearchResults.replaceChildren(); foodSearchInput.setAttribute('aria-expanded', String(foods.length > 0)); foodSearchStatus.textContent = label || (foods.length ? `${foods.length} resultado${foods.length > 1 ? 's' : ''} encontrado${foods.length > 1 ? 's' : ''}.` : 'Nenhum alimento encontrado.'); foods.forEach((food, index) => { const item = document.createElement('li'); item.className = 'food-search-result'; item.id = `food-result-${index}`; item.dataset.index = index; item.tabIndex = -1; item.setAttribute('role', 'option'); item.innerHTML = `<strong>${food.alimento}</strong><span>${foodReference(food)}</span><span>${formatNutrition(number(food.carboidratos_g), number(food.calorias_kcal))}</span>`; foodSearchResults.append(item); }); }
function selectFood(food, recent = null) { selectedFood = food; const recents = [food.id, ...getRecents().filter((id) => id !== food.id)].slice(0, 12); localStorage.setItem(recentStorageKey, JSON.stringify(recents)); $('#selected-food-name').textContent = food.alimento; $('#selected-food-reference').textContent = foodReference(food); const portion = $('#food-portion'); portion.replaceChildren(); const option = document.createElement('option'); option.value = food.id; option.textContent = food.medida_usual || 'Porção de referência'; portion.append(option); const gramsAvailable = number(food.quantidade_valor) > 0; $('#grams-mode').hidden = !gramsAvailable; $('#quantity-mode input[value="grams"]').disabled = !gramsAvailable; const grams = recent?.input_mode === 'gramas' && gramsAvailable; $('#quantity-mode input[value="grams"]').checked = grams; $('#quantity-mode input[value="portion"]').checked = !grams; $('#food-quantity').value = recent?.last_quantity || 1; $('#quantity-label').firstChild.textContent = grams ? 'Quantidade em gramas' : 'Quantidade de porções'; $('#favorite-food').textContent = getFavorites().includes(food.id) ? '★' : '☆'; $('#favorite-food').setAttribute('aria-label', getFavorites().includes(food.id) ? 'Remover dos favoritos' : 'Adicionar aos favoritos'); foodEditor.hidden = false; updateFoodPreview(); foodSearchInput.value = food.alimento; foodSearchResults.replaceChildren(); foodSearchInput.setAttribute('aria-expanded', 'false'); foodSearchStatus.textContent = 'Alimento selecionado. Ajuste a quantidade e adicione à refeição.'; }
function currentFoodCalculation() { if (!selectedFood) return { quantity: 0, unit: '', carbs: 0, calories: 0 }; const grams = $('#quantity-mode input[value="grams"]').checked; const quantity = number($('#food-quantity').value); const reference = number(selectedFood.quantidade_valor); const multiplier = grams && reference > 0 ? quantity / reference : quantity; return { quantity, unit: grams ? 'g' : (selectedFood.medida_usual || 'porção'), carbs: number(selectedFood.carboidratos_g) * multiplier, calories: number(selectedFood.calorias_kcal) * multiplier }; }
function updateFoodPreview() { const calculation = currentFoodCalculation(); $('#food-preview-carbs').textContent = format(calculation.carbs, 'g'); $('#food-preview-calories').textContent = format(calculation.calories, 'kcal'); }
foodSearchInput.addEventListener('input', () => { const query = foodSearchInput.value.trim(); renderFoodResults(query ? rankFoods(query) : [], query ? undefined : 'Digite ao menos um caractere para pesquisar.'); });
foodSearchResults.addEventListener('click', (event) => { const result = event.target.closest('.food-search-result'); if (result) { const food = currentResults[Number(result.dataset.index)]; selectFood(food, food.recentEntry || null); } });
foodSearchInput.addEventListener('keydown', (event) => { if (event.key === 'Escape') { foodSearchResults.replaceChildren(); foodSearchInput.setAttribute('aria-expanded', 'false'); return; } if (!currentResults.length) return; if (event.key === 'ArrowDown' || event.key === 'ArrowUp') { event.preventDefault(); activeResult = (activeResult + (event.key === 'ArrowDown' ? 1 : currentResults.length - 1)) % currentResults.length; [...foodSearchResults.children].forEach((item, index) => item.setAttribute('aria-selected', String(index === activeResult))); foodSearchInput.setAttribute('aria-activedescendant', `food-result-${activeResult}`); } if (event.key === 'Enter' && activeResult >= 0) { event.preventDefault(); selectFood(currentResults[activeResult]); } });
$('#quantity-mode').addEventListener('change', () => { const grams = $('#quantity-mode input[value="grams"]').checked; $('#quantity-label').firstChild.textContent = grams ? 'Quantidade em gramas' : 'Quantidade de porções'; updateFoodPreview(); });
$('#food-quantity').addEventListener('input', updateFoodPreview);
$('#favorite-food').addEventListener('click', () => { if (!selectedFood) return; const favorites = getFavorites(); const included = favorites.includes(selectedFood.id); localStorage.setItem(favoriteStorageKey, JSON.stringify(included ? favorites.filter((id) => id !== selectedFood.id) : [...favorites, selectedFood.id])); selectFood(selectedFood); });
foodEditor.addEventListener('submit', (event) => { event.preventDefault(); const calculation = currentFoodCalculation(); const status = $('#food-save-status'); if (!selectedFood || calculation.quantity <= 0) { status.textContent = 'Informe uma quantidade válida.'; $('#food-quantity').focus(); return; } const meal = $('#food-meal').value; const entry = { entryId: `${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, date: todayKey(), meal, foodId: selectedFood.id, name: selectedFood.alimento, quantity: calculation.quantity, unit: calculation.unit, carbs: calculation.carbs, calories: calculation.calories }; localStorage.setItem(foodStorageKey, JSON.stringify([...getEntries(), entry])); const allRecents = getRecentsByMeal(); const mealRecents = allRecents[meal] || []; const recent = { food_id: selectedFood.id, food_name: selectedFood.alimento, portion_id: selectedFood.id, portion_label: selectedFood.medida_usual, input_mode: $('#quantity-mode input[value="grams"]').checked ? 'gramas' : 'porcao', last_quantity: calculation.quantity, last_grams_or_ml: $('#quantity-mode input[value="grams"]').checked ? calculation.quantity : null, last_carbs_g: calculation.carbs, last_calories_kcal: calculation.calories, last_used_at: new Date().toISOString() }; allRecents[meal] = [recent, ...mealRecents.filter((item) => item.food_id !== selectedFood.id)].slice(0, 10); localStorage.setItem(recentByMealStorageKey, JSON.stringify(allRecents)); renderMeals(); status.textContent = `${selectedFood.alimento} adicionado à refeição.`; });
$('#show-recent-foods').addEventListener('click', () => { const meal = $('#food-meal').value; const recents = getRecentsByMeal()[meal] || []; const matches = recents.map((recent) => ({ food: foodIndex.find((food) => food.id === recent.food_id), recent })).filter((item) => item.food); renderFoodResults(matches.map((item) => item.food), `Recentes de ${$('#food-meal').selectedOptions[0].text}.`); foodSearchResults.querySelectorAll('.food-search-result').forEach((item, index) => { item.dataset.recentIndex = index; }); const original = currentResults; currentResults = matches.map((item) => ({ ...item.food, recentEntry: item.recent })); });
$('#show-favorite-foods').addEventListener('click', () => renderFoodResults(getFavorites().map((id) => foodIndex.find((food) => food.id === id)).filter(Boolean), 'Alimentos favoritos.'));
async function loadFoodSearch() { try { const response = await fetch('Tabela_Alimentos_Codex.json'); if (!response.ok) throw new Error(); const data = await response.json(); foodIndex = data.alimentos.map((food) => ({ ...food, search: normalizeSearchText([food.alimento, food.medida_usual, food.categoria].filter(Boolean).join(' ')) })); foodSearchInput.disabled = false; foodSearchStatus.textContent = `${foodIndex.length.toLocaleString('pt-BR')} alimentos disponíveis para pesquisa.`; } catch { foodSearchStatus.textContent = 'Não foi possível carregar a tabela de alimentos.'; } }
resetDailyEntriesIfNeeded(); loadCarbTargets(); $('#food-meal').value = suggestedMeal(); updateCorrection(); updateMonthlyTotals(); renderMeals(); loadFoodSearch();
