const $ = (selector) => document.querySelector(selector);
const number = (value) => Number.parseFloat(value) || 0;
const foodStorageKey = 'diabetes-dashboard-food-entries';
const favoriteStorageKey = 'diabetes-dashboard-food-favorites';
const recentStorageKey = 'diabetes-dashboard-food-recents';
const recentByMealStorageKey = 'recent_foods_by_meal';
const carbTargetStorageKey = 'carbohydrate_count_settings';
const dailyDateStorageKey = 'diabetes-dashboard-food-date';
const insulinHistoryStorageKey = 'diabetes-dashboard-insulin-history';
const insulinHistorySessionStorageKey = 'diabetes-dashboard-insulin-history-session';
const activeHistoryRecordStorageKey = 'diabetes-dashboard-active-history-record';
const themeToggle = $('#theme-toggle');
const foodSearchInput = $('#food-search-input');
const foodSearchResults = $('#food-search-results');
const foodSearchStatus = $('#food-search-status');
const foodEditor = $('#food-editor');
let foodIndex = [];
let currentResults = [];
let activeResult = -1;
let selectedFood = null;
let historyTimer;
const selectedHistoryIds = new Set();

const format = (value, suffix = '') => `${Number(value.toFixed(1)).toLocaleString('pt-BR')} ${suffix}`;
const formatNutrition = (carbs, calories) => `${format(carbs, 'g CHO')} · ${format(calories, 'kcal')}`;
const normalizeSearchText = (value) => String(value || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9\s]/g, ' ').replace(/\s+/g, ' ').trim();
const getStored = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key) || JSON.stringify(fallback)); } catch { return fallback; } };
const getEntries = () => getStored(foodStorageKey, []);
const getFavorites = () => getStored(favoriteStorageKey, []);
const getRecents = () => getStored(recentStorageKey, []);
const mealTypes = ['cafe_da_manha', 'almoco', 'lanche', 'jantar', 'ceia', 'outro'];
const getCarbTargets = () => getStored(carbTargetStorageKey, {});
const getRecentsByMeal = () => getStored(recentByMealStorageKey, {});
const getInsulinHistory = () => getStored(insulinHistoryStorageKey, []).map((record) => ({ ...record, id: record.id || record.createdAt, foods: record.foods || [] }));
const getHistorySession = () => { try { return JSON.parse(sessionStorage.getItem(insulinHistorySessionStorageKey) || '{}'); } catch { return {}; } };
const saveHistorySession = (session) => sessionStorage.setItem(insulinHistorySessionStorageKey, JSON.stringify(session));
const getActiveHistoryRecords = () => { try { return JSON.parse(sessionStorage.getItem(activeHistoryRecordStorageKey) || '{}'); } catch { return {}; } };
const saveActiveHistoryRecords = (records) => sessionStorage.setItem(activeHistoryRecordStorageKey, JSON.stringify(records));
const todayKey = () => new Date().toLocaleDateString('en-CA');
function suggestedMeal() { const hour = new Date().getHours(); if (hour >= 5 && hour <= 10) return 'cafe_da_manha'; if (hour <= 14) return 'almoco'; if (hour <= 17) return 'lanche'; if (hour <= 22) return 'jantar'; return 'ceia'; }
function resetDailyEntriesIfNeeded() { if (localStorage.getItem(dailyDateStorageKey) === todayKey()) return; localStorage.setItem(foodStorageKey, '[]'); localStorage.setItem(dailyDateStorageKey, todayKey()); }

function setTheme(theme) { document.documentElement.dataset.theme = theme; const dark = theme === 'dark'; const label = dark ? 'Usar tema claro' : 'Usar tema escuro'; themeToggle.setAttribute('aria-label', label); themeToggle.title = label; themeToggle.setAttribute('aria-pressed', String(dark)); }
setTheme(localStorage.getItem('diabetes-dashboard-theme') || 'light');
themeToggle.addEventListener('click', () => { const theme = document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark'; localStorage.setItem('diabetes-dashboard-theme', theme); setTheme(theme); });

function getMonthKey(offset = 0) { const date = new Date(); date.setDate(1); date.setMonth(date.getMonth() + offset); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`; }
function updateMonthlyTotals() { const totals = getStored('diabetes-dashboard-monthly-insulin', {}); const previous = $('#previous-month-insulin'); const current = $('#current-month-insulin'); if (previous) previous.textContent = format(number(totals[getMonthKey(-1)]), 'un.'); if (current) current.textContent = format(number(totals[getMonthKey()]), 'un.'); }
function getCorrectionDose() { const factor = number($('#correction-factor').value); const current = $('#current-glucose').value; const target = $('#target-glucose').value; const difference = number(current) - number(target); const canCalculate = current && target && factor > 0; return { difference, canCalculate, dose: canCalculate && difference > 0 ? difference / factor : 0 }; }
function getCarbDose() { const entries = getEntries(); const meal = entries.at(-1)?.meal; const carbs = meal ? entries.filter((entry) => entry.meal === meal).reduce((total, entry) => total + number(entry.carbs), 0) : 0; const target = number(getCarbTargets()[meal]); if (!meal || target <= 0) return { meal, canCalculate: false, dose: 0, carbs, target: 0 }; return { meal, canCalculate: true, dose: carbs / target, carbs, target }; }
function getInsulinDose() { const correction = getCorrectionDose(); const carbs = getCarbDose(); return { canCalculate: correction.canCalculate || carbs.canCalculate, dose: correction.dose + carbs.dose }; }
function buildHistorySnapshot() { const glucoseInput = $('#current-glucose'); const targetInput = $('#target-glucose'); const correction = getCorrectionDose(); const carbs = getCarbDose(); const insulin = getInsulinDose(); const entries = getEntries().filter((entry) => entry.meal === carbs.meal); if (!glucoseInput.value || !targetInput.value || !glucoseInput.validity.valid || !targetInput.validity.valid || !correction.canCalculate || !carbs.meal || !carbs.canCalculate || !entries.length || ![correction.difference, carbs.carbs, carbs.dose, insulin.dose].every(Number.isFinite)) return null; const foods = entries.map((entry) => ({ name: entry.name, quantity: entry.quantity, unit: entry.unit, carbs: entry.carbs })); const sourceFingerprint = JSON.stringify({ meal: carbs.meal, currentGlucose: number(glucoseInput.value), targetGlucose: number(targetInput.value), glucoseDifference: correction.difference, mealCarbs: carbs.carbs, mealDose: carbs.dose, totalDose: insulin.dose, foods: entries.map((entry) => ({ id: entry.entryId, quantity: entry.quantity, unit: entry.unit, carbs: entry.carbs })) }); return { meal: carbs.meal, currentGlucose: number(glucoseInput.value), targetGlucose: number(targetInput.value), glucoseDifference: correction.difference, mealCarbs: carbs.carbs, mealDose: carbs.dose, totalDose: insulin.dose, foods, sourceFingerprint }; }
const formatHistoryValue = (value, suffix) => value === undefined || value === null || value === '' ? '—' : format(number(value), suffix);
function renderHistory() { const body = $('#insulin-history'); const meals = { cafe_da_manha: 'Café da manhã', almoco: 'Almoço', lanche: 'Lanche', jantar: 'Jantar', ceia: 'Ceia', outro: 'Outro' }; const records = getInsulinHistory().sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)); [...selectedHistoryIds].forEach((id) => { if (!records.some((record) => record.id === id)) selectedHistoryIds.delete(id); }); body.replaceChildren(); if (!records.length) { const row = document.createElement('tr'); const cell = document.createElement('td'); cell.colSpan = 10; cell.textContent = 'Nenhum cálculo registrado.'; row.append(cell); body.append(row); } else records.forEach((record) => { const row = document.createElement('tr'); const selector = document.createElement('input'); selector.type = 'checkbox'; selector.className = 'history-select'; selector.value = record.id; selector.checked = selectedHistoryIds.has(record.id); const selectCell = document.createElement('td'); selectCell.append(selector); row.append(selectCell); const foods = record.foods.length ? record.foods.map((food) => `${food.name} ${food.quantity} ${food.unit}`).join(' | ') : '—'; [record.createdAt ? new Date(record.createdAt).toLocaleString('pt-BR') : '—', meals[record.meal] || record.meal || '—', formatHistoryValue(record.currentGlucose, 'mg/dL'), formatHistoryValue(record.targetGlucose, 'mg/dL'), record.glucoseDifference === undefined || record.glucoseDifference === null ? '—' : `${record.glucoseDifference > 0 ? '+' : ''}${formatHistoryValue(record.glucoseDifference, 'mg/dL')}`, formatHistoryValue(record.mealCarbs, 'g CHO'), formatHistoryValue(record.mealDose, 'un.'), formatHistoryValue(record.totalDose, 'un.'), foods].forEach((value) => { const cell = document.createElement('td'); cell.textContent = value; row.append(cell); }); body.append(row); }); const selectAll = $('#select-all-history'); selectAll.checked = records.length > 0 && selectedHistoryIds.size === records.length; selectAll.indeterminate = selectedHistoryIds.size > 0 && selectedHistoryIds.size < records.length; }
function saveOrUpdateHistory(snapshot) { const history = getInsulinHistory(); const activeRecords = getActiveHistoryRecords(); const active = activeRecords[snapshot.meal]; const now = Date.now(); const activeIndex = active && now - active.lastUpdatedAt <= 30 * 60 * 1000 ? history.findIndex((record) => record.id === active.id) : -1; if (activeIndex >= 0) { if (history[activeIndex].sourceFingerprint === snapshot.sourceFingerprint) return; history[activeIndex] = { ...history[activeIndex], ...snapshot, updatedAt: new Date(now).toISOString() }; } else { if (!active && history.at(-1)?.sourceFingerprint === snapshot.sourceFingerprint) return; const createdAt = new Date(now).toISOString(); const record = { id: crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, createdAt, updatedAt: createdAt, ...snapshot }; history.push(record); activeRecords[snapshot.meal] = { id: record.id, meal: snapshot.meal, lastUpdatedAt: now }; } activeRecords[snapshot.meal] = { id: history[activeIndex >= 0 ? activeIndex : history.length - 1].id, meal: snapshot.meal, lastUpdatedAt: now }; saveActiveHistoryRecords(activeRecords); localStorage.setItem(insulinHistoryStorageKey, JSON.stringify(history)); renderHistory(); }
function scheduleHistoryFromUserAction() { clearTimeout(historyTimer); if (!buildHistorySnapshot()) return; historyTimer = setTimeout(() => { const snapshot = buildHistorySnapshot(); if (snapshot) saveOrUpdateHistory(snapshot); }, 2000); }
function updateCorrection() { const current = $('#current-glucose').value; const target = $('#target-glucose').value; const correction = getCorrectionDose(); const carbs = getCarbDose(); const insulin = getInsulinDose(); $('#glucose-difference').textContent = current && target ? `${correction.difference > 0 ? '+' : ''}${format(correction.difference, 'mg/dL')}` : '—'; $('#meal-dose').textContent = carbs.canCalculate ? `${format(carbs.carbs, 'g CHO')} ÷ ${format(carbs.target, 'g')} = ${format(carbs.dose, 'un.')}` : '—'; $('#correction-dose').textContent = insulin.canCalculate ? format(insulin.dose, 'un.') : '—'; }
['#target-glucose', '#correction-factor', '#current-glucose'].forEach((id) => $(id).addEventListener('input', () => { updateCorrection(); scheduleHistoryFromUserAction(); }));
['#target-glucose', '#correction-factor'].forEach((id) => { const key = id === '#target-glucose' ? 'diabetes-dashboard-target' : 'diabetes-dashboard-correction-factor'; const saved = localStorage.getItem(key) || (id === '#correction-factor' && localStorage.getItem('diabetes-dashboard-correction-insulin')); if (saved) $(id).value = saved; });
$('#save-parameters').addEventListener('click', () => { const status = $('#target-save-status'); const target = $('#target-glucose'); const factor = $('#correction-factor'); if (![target, factor].some((input) => input.value)) { status.textContent = 'Informe o alvo ou o valor de correção para gravar.'; target.focus(); return; } if (![target, factor].every((input) => !input.value || input.validity.valid)) { status.textContent = 'Informe valores válidos para gravar.'; return; } if (target.value) localStorage.setItem('diabetes-dashboard-target', target.value); if (factor.value) localStorage.setItem('diabetes-dashboard-correction-factor', factor.value); const dose = getInsulinDose().dose; if (dose > 0) { const totals = getStored('diabetes-dashboard-monthly-insulin', {}); const month = getMonthKey(); totals[month] = number(totals[month]) + dose; localStorage.setItem('diabetes-dashboard-monthly-insulin', JSON.stringify(totals)); updateMonthlyTotals(); status.textContent = 'Aplicação gravada no total deste mês.'; } else status.textContent = 'Parâmetros salvos; nenhuma aplicação foi adicionada ao mês.'; });

function loadCarbTargets() { const targets = getCarbTargets(); document.querySelectorAll('.carb-target').forEach((input) => { input.value = targets[input.dataset.meal] ?? ''; }); }
$('#save-carb-targets').addEventListener('click', () => { const inputs = [...document.querySelectorAll('.carb-target')]; const invalid = inputs.find((input) => input.value && !input.validity.valid); const status = $('#carb-target-status'); if (invalid) { status.textContent = 'Informe valores em gramas válidos.'; invalid.focus(); return; } const targets = {}; inputs.forEach((input) => { if (input.value !== '') targets[input.dataset.meal] = number(input.value); }); localStorage.setItem(carbTargetStorageKey, JSON.stringify(targets)); renderMeals(); status.textContent = 'Metas de carboidratos gravadas neste navegador.'; });

function renderMeals() { const entries = getEntries(); const targets = getCarbTargets(); const currentMeal = entries.at(-1)?.meal; let currentMealCarbs = 0; let currentMealCalories = 0; document.querySelectorAll('.meal-card').forEach((card) => { const list = card.querySelector('.meal-items'); const items = entries.filter((entry) => entry.meal === card.dataset.meal); const carbs = items.reduce((total, entry) => total + entry.carbs, 0); const calories = items.reduce((total, entry) => total + entry.calories, 0); const target = number(targets[card.dataset.meal]); if (card.dataset.meal === currentMeal) { currentMealCarbs = carbs; currentMealCalories = calories; } list.replaceChildren(); card.querySelector('.meal-empty').hidden = Boolean(items.length); const progress = card.querySelector('.meal-progress'); progress.textContent = target > 0 ? `Meta: ${format(target, 'g')} · Consumido: ${format(carbs, 'g')} · Restante: ${format(target - carbs, 'g')}` : `Consumido: ${format(carbs, 'g')} · Meta não configurada`; items.forEach((entry) => { const item = document.createElement('li'); item.className = 'meal-item'; const copy = document.createElement('span'); copy.innerHTML = `<strong>${entry.name}</strong><small>${entry.quantity} ${entry.unit} · ${formatNutrition(entry.carbs, entry.calories)}</small>`; const remove = document.createElement('button'); remove.type = 'button'; remove.className = 'remove-food'; remove.dataset.entryId = entry.entryId; remove.setAttribute('aria-label', `Remover ${entry.name}`); remove.textContent = '×'; item.append(copy, remove); list.append(item); }); card.querySelector('.meal-total strong').textContent = formatNutrition(carbs, calories); }); $('#daily-food-total').textContent = formatNutrition(currentMealCarbs, currentMealCalories); updateCorrection(); }
$('#meal-grid').addEventListener('click', (event) => { const button = event.target.closest('.remove-food'); if (!button) return; localStorage.setItem(foodStorageKey, JSON.stringify(getEntries().filter((entry) => entry.entryId !== button.dataset.entryId))); renderMeals(); });

function foodReference(food) { const amount = Number.isFinite(Number(food.quantidade_valor)) ? `${food.quantidade_valor} ${food.quantidade_unidade === 'g' ? 'g' : 'g/ml'}` : 'quantidade não informada'; return `${food.medida_usual || 'Medida não informada'} · ${amount}`; }
function rankFoods(query, foods = foodIndex) { const terms = normalizeSearchText(query).split(' ').filter(Boolean); const favorites = new Set(getFavorites()); const recent = getRecents(); const recentRank = new Map(recent.map((id, index) => [id, index])); return foods.filter((food) => !terms.length || terms.every((term) => food.search.includes(term))).sort((a, b) => { const score = (food) => (favorites.has(food.id) ? 40 : 0) + (recentRank.has(food.id) ? 20 - Math.min(recentRank.get(food.id), 19) : 0) + (food.search.startsWith(normalizeSearchText(query)) ? 10 : 0); return score(b) - score(a) || a.alimento.localeCompare(b.alimento, 'pt-BR'); }).slice(0, 12); }
function renderFoodResults(foods, label) { currentResults = foods; activeResult = -1; foodSearchResults.replaceChildren(); foodSearchInput.setAttribute('aria-expanded', String(foods.length > 0)); foodSearchStatus.textContent = label || (foods.length ? `${foods.length} resultado${foods.length > 1 ? 's' : ''} encontrado${foods.length > 1 ? 's' : ''}.` : 'Nenhum alimento encontrado.'); foods.forEach((food, index) => { const item = document.createElement('li'); item.className = 'food-search-result'; item.id = `food-result-${index}`; item.dataset.index = index; item.tabIndex = -1; item.setAttribute('role', 'option'); item.innerHTML = `<strong>${food.alimento}</strong><span>${foodReference(food)}</span><span>${formatNutrition(number(food.carboidratos_g), number(food.calorias_kcal))}</span>`; foodSearchResults.append(item); }); }
function selectFood(food, recent = null) { selectedFood = food; const recents = [food.id, ...getRecents().filter((id) => id !== food.id)].slice(0, 12); localStorage.setItem(recentStorageKey, JSON.stringify(recents)); $('#selected-food-name').textContent = food.alimento; $('#selected-food-reference').textContent = foodReference(food); const portion = $('#food-portion'); portion.replaceChildren(); const option = document.createElement('option'); option.value = food.id; option.textContent = food.medida_usual || 'Porção de referência'; portion.append(option); const gramsAvailable = number(food.quantidade_valor) > 0; $('#grams-mode').hidden = !gramsAvailable; $('#quantity-mode input[value="grams"]').disabled = !gramsAvailable; const grams = recent?.input_mode === 'gramas' && gramsAvailable; $('#quantity-mode input[value="grams"]').checked = grams; $('#quantity-mode input[value="portion"]').checked = !grams; $('#food-quantity').value = recent?.last_quantity || 1; $('#quantity-label').firstChild.textContent = grams ? 'Quantidade em gramas' : 'Quantidade de porções'; $('#favorite-food').textContent = getFavorites().includes(food.id) ? '★' : '☆'; $('#favorite-food').setAttribute('aria-label', getFavorites().includes(food.id) ? 'Remover dos favoritos' : 'Adicionar aos favoritos'); foodEditor.hidden = false; updateFoodPreview(); foodSearchInput.value = food.alimento; foodSearchResults.replaceChildren(); foodSearchInput.setAttribute('aria-expanded', 'false'); foodSearchStatus.textContent = 'Alimento selecionado. Ajuste a quantidade e adicione à refeição.'; }
function currentFoodCalculation() { if (!selectedFood) return { quantity: 0, unit: '', carbs: 0, calories: 0 }; const grams = $('#quantity-mode input[value="grams"]').checked; const quantity = number($('#food-quantity').value); const reference = number(selectedFood.quantidade_valor); const multiplier = grams && reference > 0 ? quantity / reference : quantity; return { quantity, unit: grams ? 'g' : (selectedFood.medida_usual || 'porção'), carbs: number(selectedFood.carboidratos_g) * multiplier, calories: number(selectedFood.calorias_kcal) * multiplier }; }
function updateFoodPreview() { const calculation = currentFoodCalculation(); $('#food-preview-carbs').textContent = format(calculation.carbs, 'g'); $('#food-preview-calories').textContent = format(calculation.calories, 'kcal'); }
foodSearchInput.addEventListener('input', () => { const query = foodSearchInput.value.trim(); renderFoodResults(query ? rankFoods(query) : [], query ? undefined : 'Digite ao menos um caractere para pesquisar.'); });
foodSearchResults.addEventListener('click', (event) => { const result = event.target.closest('.food-search-result'); if (result) { const food = currentResults[Number(result.dataset.index)]; selectFood(food, food.recentEntry || null); } });
foodSearchInput.addEventListener('keydown', (event) => { if (event.key === 'Escape') { foodSearchResults.replaceChildren(); foodSearchInput.setAttribute('aria-expanded', 'false'); return; } if (!currentResults.length) return; if (event.key === 'ArrowDown' || event.key === 'ArrowUp') { event.preventDefault(); activeResult = (activeResult + (event.key === 'ArrowDown' ? 1 : currentResults.length - 1)) % currentResults.length; [...foodSearchResults.children].forEach((item, index) => item.setAttribute('aria-selected', String(index === activeResult))); foodSearchInput.setAttribute('aria-activedescendant', `food-result-${activeResult}`); } if (event.key === 'Enter' && activeResult >= 0) { event.preventDefault(); selectFood(currentResults[activeResult]); } });
$('#quantity-mode').addEventListener('change', () => { const grams = $('#quantity-mode input[value="grams"]').checked; $('#quantity-label').firstChild.textContent = grams ? 'Quantidade em gramas' : 'Quantidade de porções'; updateFoodPreview(); });
$('#food-quantity').addEventListener('input', updateFoodPreview);
$('#favorite-food').addEventListener('click', () => { if (!selectedFood) return; const favorites = getFavorites(); const included = favorites.includes(selectedFood.id); localStorage.setItem(favoriteStorageKey, JSON.stringify(included ? favorites.filter((id) => id !== selectedFood.id) : [...favorites, selectedFood.id])); selectFood(selectedFood); });
foodEditor.addEventListener('submit', (event) => { event.preventDefault(); const calculation = currentFoodCalculation(); const status = $('#food-save-status'); if (!selectedFood || calculation.quantity <= 0) { status.textContent = 'Informe uma quantidade válida.'; $('#food-quantity').focus(); return; } const meal = $('#food-meal').value; const entry = { entryId: `${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, date: todayKey(), meal, foodId: selectedFood.id, name: selectedFood.alimento, quantity: calculation.quantity, unit: calculation.unit, carbs: calculation.carbs, calories: calculation.calories }; localStorage.setItem(foodStorageKey, JSON.stringify([...getEntries(), entry])); const allRecents = getRecentsByMeal(); const mealRecents = allRecents[meal] || []; const recent = { food_id: selectedFood.id, food_name: selectedFood.alimento, portion_id: selectedFood.id, portion_label: selectedFood.medida_usual, input_mode: $('#quantity-mode input[value="grams"]').checked ? 'gramas' : 'porcao', last_quantity: calculation.quantity, last_grams_or_ml: $('#quantity-mode input[value="grams"]').checked ? calculation.quantity : null, last_carbs_g: calculation.carbs, last_calories_kcal: calculation.calories, last_used_at: new Date().toISOString() }; allRecents[meal] = [recent, ...mealRecents.filter((item) => item.food_id !== selectedFood.id)].slice(0, 10); localStorage.setItem(recentByMealStorageKey, JSON.stringify(allRecents)); renderMeals(); status.textContent = `${selectedFood.alimento} adicionado à refeição.`; });
$('#show-recent-foods').addEventListener('click', () => { const meal = $('#food-meal').value; const recents = getRecentsByMeal()[meal] || []; const matches = recents.map((recent) => ({ food: foodIndex.find((food) => food.id === recent.food_id), recent })).filter((item) => item.food); renderFoodResults(matches.map((item) => item.food), `Recentes de ${$('#food-meal').selectedOptions[0].text}.`); foodSearchResults.querySelectorAll('.food-search-result').forEach((item, index) => { item.dataset.recentIndex = index; }); const original = currentResults; currentResults = matches.map((item) => ({ ...item.food, recentEntry: item.recent })); });
$('#show-favorite-foods').addEventListener('click', () => renderFoodResults(getFavorites().map((id) => foodIndex.find((food) => food.id === id)).filter(Boolean), 'Alimentos favoritos.'));
async function loadFoodSearch() { try { const response = await fetch('Tabela_Alimentos_Codex.json'); if (!response.ok) throw new Error(); const data = await response.json(); foodIndex = data.alimentos.map((food) => ({ ...food, search: normalizeSearchText([food.alimento, food.medida_usual, food.categoria].filter(Boolean).join(' ')) })); foodSearchInput.disabled = false; foodSearchStatus.textContent = `${foodIndex.length.toLocaleString('pt-BR')} alimentos disponíveis para pesquisa.`; } catch { foodSearchStatus.textContent = 'Não foi possível carregar a tabela de alimentos.'; } }
$('#meal-grid').addEventListener('click', (event) => { if (event.target.closest('.remove-food')) setTimeout(scheduleHistoryFromUserAction); });
foodEditor.addEventListener('submit', () => setTimeout(scheduleHistoryFromUserAction));
$('#save-carb-targets').addEventListener('click', () => setTimeout(scheduleHistoryFromUserAction));
$('#insulin-history').addEventListener('change', (event) => { if (!event.target.matches('.history-select')) return; if (event.target.checked) selectedHistoryIds.add(event.target.value); else selectedHistoryIds.delete(event.target.value); renderHistory(); });
$('#select-all-history').addEventListener('change', (event) => { const records = getInsulinHistory(); if (event.target.checked) records.forEach((record) => selectedHistoryIds.add(record.id)); else selectedHistoryIds.clear(); renderHistory(); });
$('#delete-history').addEventListener('click', () => { const status = $('#history-status'); if (!selectedHistoryIds.size) { status.textContent = 'Selecione ao menos um registro.'; return; } if (window.prompt('Informe a senha para excluir os registros selecionados:') !== 'Lidy243010@') { status.textContent = 'Senha incorreta'; return; } if (!window.confirm('Deseja realmente excluir os registros selecionados?')) return; const removed = selectedHistoryIds; const history = getInsulinHistory().filter((record) => !removed.has(record.id)); const session = getHistorySession(); Object.keys(session).forEach((meal) => { if (removed.has(session[meal])) delete session[meal]; }); saveHistorySession(session); localStorage.setItem(insulinHistoryStorageKey, JSON.stringify(history)); selectedHistoryIds.clear(); renderHistory(); status.textContent = 'Registros selecionados excluídos.'; });
function setView(view) { const history = view === 'history'; document.querySelectorAll('.app-shell > .hero, .app-shell > .panel:not(#history-view), .app-shell > footer').forEach((element) => { element.hidden = history; }); $('#history-view').hidden = !history; $('#control-tab').setAttribute('aria-selected', String(!history)); $('#history-tab').setAttribute('aria-selected', String(history)); }
$('#control-tab').addEventListener('click', () => setView('control'));
$('#history-tab').addEventListener('click', () => setView('history'));
document.querySelector('.hero h1').textContent = 'Controle Glicemia V2';
const historyMealLabels = { cafe_da_manha: 'Café da manhã', almoco: 'Almoço', lanche: 'Lanche', jantar: 'Jantar', ceia: 'Ceia', outro: 'Outro' };
function historyExportRows() { return getInsulinHistory().sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)).map((record) => ({ dataHora: new Date(record.createdAt).toLocaleString('pt-BR'), refeicao: historyMealLabels[record.meal] || record.meal, glicemia: number(record.currentGlucose), alvo: number(record.targetGlucose), diferenca: number(record.glucoseDifference), cho: number(record.mealCarbs), doseRefeicao: number(record.mealDose), totalDose: number(record.totalDose), alimentos: record.foods.map((food) => `${food.name} ${food.quantity} ${food.unit}`).join(' | ') })); }
function exportHistoryPdf() { const rows = historyExportRows(); const status = $('#history-status'); if (!rows.length) { status.textContent = 'Não há registros para exportar.'; return; } if (!window.jspdf?.jsPDF) { status.textContent = 'Não foi possível carregar a biblioteca de PDF.'; return; } const doc = new window.jspdf.jsPDF({ orientation: 'landscape', unit: 'pt', format: 'a4' }); if (typeof doc.autoTable !== 'function') { status.textContent = 'Não foi possível carregar a tabela do PDF.'; return; } doc.setFontSize(14); doc.text('Controle Glicemia V2', 40, 36); doc.setFontSize(11); doc.text('Histórico', 40, 52); doc.setFontSize(8); doc.text(`Gerado em ${new Date().toLocaleString('pt-BR')}`, 40, 66); doc.autoTable({ startY: 78, head: [['Data/Hora', 'Refeição', 'Glicemia', 'Alvo', 'Diferença', 'CHO da refeição', 'Dose da refeição', 'Total a aplicar', 'Alimentos']], body: rows.map((row) => [row.dataHora, row.refeicao, row.glicemia, row.alvo, row.diferenca, row.cho, row.doseRefeicao, row.totalDose, row.alimentos]), styles: { fontSize: 5.5, cellPadding: 3, overflow: 'linebreak' }, columnStyles: { 8: { cellWidth: 170 } }, margin: { left: 22, right: 22 } }); doc.save('historico-controle-glicemia.pdf'); }
function exportHistoryExcel() { const rows = historyExportRows(); const status = $('#history-status'); if (!rows.length) { status.textContent = 'Não há registros para exportar.'; return; } if (!window.XLSX) { status.textContent = 'Não foi possível carregar a biblioteca de Excel.'; return; } const sheetRows = rows.map((row) => ({ 'Data/Hora': row.dataHora, 'Refeição': row.refeicao, 'Glicemia (mg/dL)': row.glicemia, 'Alvo (mg/dL)': row.alvo, 'Diferença (mg/dL)': row.diferenca, 'CHO (g)': row.cho, 'Dose refeição (un.)': row.doseRefeicao, 'Total a aplicar (un.)': row.totalDose, Alimentos: row.alimentos })); const workbook = window.XLSX.utils.book_new(); const sheet = window.XLSX.utils.json_to_sheet(sheetRows); sheet['!cols'] = [{ wch: 18 }, { wch: 18 }, { wch: 18 }, { wch: 15 }, { wch: 19 }, { wch: 12 }, { wch: 20 }, { wch: 22 }, { wch: 70 }]; window.XLSX.utils.book_append_sheet(workbook, sheet, 'Histórico'); window.XLSX.writeFile(workbook, 'historico-controle-glicemia.xlsx'); }
['pdf', 'excel'].forEach((type) => { const button = document.createElement('button'); button.type = 'button'; button.id = `export-history-${type}`; button.textContent = `Exportar ${type === 'pdf' ? 'PDF' : 'Excel'}`; button.addEventListener('click', type === 'pdf' ? exportHistoryPdf : exportHistoryExcel); $('.history-actions').append(button); });
resetDailyEntriesIfNeeded(); loadCarbTargets(); $('#food-meal').value = suggestedMeal(); updateCorrection(); updateMonthlyTotals(); renderMeals(); renderHistory(); setView('control'); loadFoodSearch();
